title: MoStories
tagline: Grab a cup of Joe and read some MoStories

author: 
  name: Mohammad Khan
  url: https://mohammadkhan-3.github.io/resume/
  
# title: Hydure
# tagline: A concise two-column blog theme for Jekyll

# author:
#   name: Song-Zi Vong
#   url: https://twitter.com/zivong91

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 3

tags_path: /tags/
categories_path: /categories/
